### ISSUE TITLE
Doesn't support fudge/fate dice

### ISSUE THREAD

**Issue by Glutnix** [lvonkacsoh/Flow.Launcher.RollDice#4]
The typical fate dice roll is notated `4dF`.

A fate dice is typically a six sided dice, two sides showing +, two sides blank, and two sides showing -. You could probably just implement it as a d[-1,0,1].

For some advanced dice notation, you might want to see if there's a python library for handling that. I don't know, personally.

**Comment by lvonkacsoh** [comment]
Good <time zone related greeting>! Thanks for the suggestion. "Currently" I am [rewriting](https://github.com/lvonkacsoh/Flow.Launcher.RollDice/tree/feat/rework) the plugin since it current release has too many issues. Sadly so does my life right now haha. Whenever things stabilise I'll come back and continue my work on it. Since your suggestion sounds like a fairly good idea, I'll try to add it to the next release 🙂

**Comment by lvonkacsoh** [comment]
Hello @Glutnix I just published a new release which includes your requested functionality. I hope it is to your liking 🙂 Flow should pick up the update within the next hours.
